### ISSUE TITLE
Relation to bsky-watch/plc-mirror ?

### ISSUE THREAD

**Issue by mrd0ll4r** [uabluerail/indexer#2]
Hello! Thanks for your work! I've been running a PLC mirror for local queries for some time now using https://github.com/bsky-watch/plc-mirror
I just noticed that that fork is diverging from this repo, even though you're seemingly the same people working on both projects, which got me confused.

For my use case, it would be preferable to have the different components of the indexer separated. I plan on running an indexer at some point in the future, but not yet. As such, for now I'm running off https://github.com/bsky-watch/plc-mirror with a few patches on top, but I'm worried it might diverge from this repo and I'm going to be stuck reconciliating different forks to rebase on top of.
I know my use case is different than the full indexer for now (e.g., I use a named volume for Postgres data instead of mounting it at a specific directory, because the PLC database is not that big). I'm not asking you to tailor your project to suit my needs, I can always apply patches on top.

Could you let me know what the plans for the two repositories and/or the system as a whole are?

**Comment by imax9000** [comment]
The plan is to keep https://github.com/bsky-watch/plc-mirror separate. I initially have written it in this repo, but it's useful on its own as well, so I extracted it into a fork.

I myself run https://github.com/bsky-watch/plc-mirror, and disable the mirror that resides in this repo. I nuke the whole database from time to time, to experiment with new approaches, but having to re-sync plc every time became a nuisance, so now I just run it separately.

I should probably take some time to delete plc mirror from this repo and update docs and configs to use the separate one.

As for diverging, you don't have to worry about that. The interface of the mirror is extremely simple ("/${did} route returns the DID document") so there shouldn't be any incompatibility regardless of which codebase is used. In fact, https://github.com/bsky-watch/plc-mirror has some improvements to better support the current rate of updates, which I didn't backport here.

**Comment by imax9000** [comment]
Also, if your patches can be useful for others - feel free to send a PR to that repo.

**Comment by mrd0ll4r** [comment]
Hey,
thank you!
Some of the patches are pretty opinionated, but some might be useful. I'll make sure to upstream those when applicable!
Best
